name: Build AsyncRAT

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v5

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Download .NET Framework 4.0 Redistributable
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://download.microsoft.com/download/9/5/a/95a9616b-7a37-4af6-bc36-d6ea96c8daae/dotNetFx40_Full_x86_x64.exe" -OutFile "dotNetFx40.exe"

    - name: Install .NET Framework 4.0
      shell: cmd
      run: |
        dotNetFx40.exe /q /norestart

    # Install NuGet packages
    - name: Install NuGet Packages
      run: nuget restore AsyncRAT-C#/AsyncRAT-Sharp.sln

    # Build solution
    - name: Build solution
      run: msbuild -nologo -v:m -p:Configuration=${{ matrix.configuration }} AsyncRAT-C#/AsyncRAT-Sharp.sln
      
    # Upload artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v5
      with:
        name: AsyncRAT-${{ matrix.configuration }}
        path: ${{ github.workspace }}\AsyncRAT-C#\Binaries\${{ matrix.configuration }}\
